name: APPSTORE

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          npm install -g pnpm
          pnpm install

      - name: Build
        run: npm run build
        env:
          DOC_ENV: production
          NODE_OPTIONS: --max-old-space-size=4096

      - name: List dist folder
        run: ls -la dist-${{ github.run_id }}  # 列出 dist 目录下的文件以确认构建成功

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.run_id }}
          path: dist/

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.APP_TOKEN }}
          artifact_name: dist-${{ github.run_id }}  # 保持与上传步骤一致
          timeout: 600000
          error_count: 10
          reporting_interval: 5000

      - name: Cleanup
        run: rm -rf dist-${{ github.run_id }}
