name: APPSTORE

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          npm install -g pnpm
          pnpm install

      - name: Build
        run: npm run build
        env:
          DOC_ENV: production
          NODE_OPTIONS: --max-old-space-size=4096

      - name: List dist folder
        run: ls -la dist  # 调试步骤，确保 dist 文件夹存在并有文件

      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.APP_TOKEN }}
          id: deployment
          branch: gh-pages
          folder: dist
          force: true
          commit-message: appstore deploy

      - name: Cleanup
        run: rm -rf dist
